### ISSUE TITLE
Win 10 64bit installs but does not run // Code does not compile // Missing AstroMath library

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/ImagePlanner#2]
Two things hopefully you can help with. The setups you provide don't work nor does the code compile. The 32bit version will not install on Win10 64bit, so, I installed the 64bit version. When trying to open the executable which is less than 400 bytes, nothing runs.

I also tried to compile in VS 2019 and I am missing a library called Astromath.

Can you help fix either of these issues. Ie. provide the library or a build that works in Windows 10 64bit.

Thanks
Dale

**Comment by rrskybox** [comment]
I am unable to replicate this issue, so I just have to make sure that we're both doing the same thing.  If you're able to compile in 
VS, then I'm pretty sure you know your way around a keyboard.  That's good.  Let's try to get the zip to install and run first, then address the compile problem you're seeing.

Once installed, the "executable" is small (390B),  but it's just a link (application reference) to the actual code which is stored elsewhere.   So that's as expected.

So, just to make sure, have you run TSX 64 once in adminstrator mode?  (This registers the TSX  libraries for other apps.)  This is usually the culprit.  You should only run TSX in this mode once, then kill it.  TSX shouldn't be running in administrator mode normally.  Let's start there.

**Comment by astromiester1** [comment]
Got it to publish... Runs ok... Sweet program... Followed your instructions and it worked. Thanks.. Your the man...

**Comment by rrskybox** [comment]
Good deal.  Let me know if anything else comes up.
